# File: .github/workflows/pages.yml
name: Deploy GitHub Pages

# Trigger on any push to main
on:
  push:
    branches: [ main ]

# Allow the workflow to publish to Pages
permissions:
  pages: write   # grants the Pages API write access
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configure the Pages deployment
      - name: Configure Pages
        uses: actions/configure-pages@v3

      # 3. Upload the `docs/` folder as the artifact to deploy
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

      # 4. Deploy the artifact to GitHub Pages
      - name: Deploy to Pages
        uses: actions/deploy-pages@v1
